spring.application.name=model-router
spring.config.import=optional:file:.env[.properties]
spring.ai.anthropic.api-key=${ANTHROPIC_API_KEY}
spring.ai.typesafe.api-key=${TYPESAFE_AI_API_KEY}

spring.ai.anthropic.custom-headers.X-Anthropic-Beta=server-side-fallback-2026-07-01